from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(600, 450)
        SettingsDialog.setWindowTitle("Sistem ve Kullanıcı Ayarları")       
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")        
        self.tabWidget = QtWidgets.QTabWidget(SettingsDialog)
        self.tabWidget.setObjectName("tabWidget")    
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.layout_general = QtWidgets.QVBoxLayout(self.tab_general)       
        self.groupBox_status = QtWidgets.QGroupBox(self.tab_general)
        self.groupBox_status.setTitle("Sistem Durumu")
        self.layout_status = QtWidgets.QVBoxLayout(self.groupBox_status)
        self.lblStatus = QtWidgets.QLabel(self.groupBox_status)
        self.lblStatus.setText("Veritabanı Durumu: Kontrol ediliyor...")
        self.layout_status.addWidget(self.lblStatus)
        self.layout_general.addWidget(self.groupBox_status)  
        self.groupBox_pass = QtWidgets.QGroupBox(self.tab_general)
        self.groupBox_pass.setTitle("Şifremi Değiştir (Admin)")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_pass)        
        self.lineOldPass = QtWidgets.QLineEdit(self.groupBox_pass)
        self.lineOldPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineOldPass.setPlaceholderText("Eski Şifre")
        self.formLayout.addRow("Eski Şifre:", self.lineOldPass)        
        self.lineNewPass = QtWidgets.QLineEdit(self.groupBox_pass)
        self.lineNewPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineNewPass.setPlaceholderText("Yeni Şifre")
        self.formLayout.addRow("Yeni Şifre:", self.lineNewPass)       
        self.btnUpdatePass = QtWidgets.QPushButton(self.groupBox_pass)
        self.btnUpdatePass.setText("Güncelle")
        self.formLayout.addRow(self.btnUpdatePass)        
        self.layout_general.addWidget(self.groupBox_pass)
        self.layout_general.addStretch()
        self.tabWidget.addTab(self.tab_general, "Genel & Şifre")        
        self.tab_users = QtWidgets.QWidget()
        self.tab_users.setObjectName("tab_users")
        self.layout_users = QtWidgets.QHBoxLayout(self.tab_users)    
        self.layout_left = QtWidgets.QVBoxLayout()
        self.label_list = QtWidgets.QLabel(self.tab_users)
        self.label_list.setText("Kayıtlı Kullanıcılar:")
        self.layout_left.addWidget(self.label_list)
        self.listUsers = QtWidgets.QListWidget(self.tab_users)
        self.layout_left.addWidget(self.listUsers)        
        self.btnDeleteUser = QtWidgets.QPushButton(self.tab_users)
        self.btnDeleteUser.setText("Seçili Kullanıcıyı Sil")
        self.btnDeleteUser.setStyleSheet("background-color: #e74c3c; color: white; font-weight: bold;")
        self.layout_left.addWidget(self.btnDeleteUser)
        self.layout_users.addLayout(self.layout_left, 60)        
        self.groupBox_add = QtWidgets.QGroupBox(self.tab_users)
        self.groupBox_add.setTitle("Yeni Kullanıcı Ekle")
        self.layout_right = QtWidgets.QVBoxLayout(self.groupBox_add)        
        self.label_u = QtWidgets.QLabel("Ad:")
        self.layout_right.addWidget(self.label_u)
        self.lineNewUsername = QtWidgets.QLineEdit(self.groupBox_add)
        self.lineNewUsername.setPlaceholderText("Kullanıcı Adı")
        self.layout_right.addWidget(self.lineNewUsername)        
        self.label_p = QtWidgets.QLabel("Şifre:")
        self.layout_right.addWidget(self.label_p)
        self.lineNewUserPass = QtWidgets.QLineEdit(self.groupBox_add)
        self.lineNewUserPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineNewUserPass.setPlaceholderText("Şifre")
        self.layout_right.addWidget(self.lineNewUserPass)        
        self.btnAddUser = QtWidgets.QPushButton(self.groupBox_add)
        self.btnAddUser.setText("Kullanıcıyı Ekle")
        self.btnAddUser.setStyleSheet("background-color: #27ae60; color: white; font-weight: bold;")
        self.layout_right.addWidget(self.btnAddUser)
        self.layout_right.addStretch()        
        self.layout_users.addWidget(self.groupBox_add, 40)
        self.tabWidget.addTab(self.tab_users, "Kullanıcı Yönetimi")        
        self.verticalLayout.addWidget(self.tabWidget)        
        self.btnClose = QtWidgets.QPushButton(SettingsDialog)
        self.btnClose.setText("Kapat")
        self.verticalLayout.addWidget(self.btnClose)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)