from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HelpScreen(object):
    def setupUi(self, HelpScreen):
        HelpScreen.setObjectName("HelpScreen")
        HelpScreen.resize(900, 600)       
        self.verticalLayout = QtWidgets.QVBoxLayout(HelpScreen)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.label_title = QtWidgets.QLabel(HelpScreen)
        font_title = QtGui.QFont()
        font_title.setPointSize(18)
        font_title.setBold(True)
        self.label_title.setFont(font_title)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setText("Sistem Kullanım Kılavuzu")
        self.verticalLayout.addWidget(self.label_title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.groupBox_topics = QtWidgets.QGroupBox("Konu Başlıkları", HelpScreen)
        self.layout_topics = QtWidgets.QVBoxLayout(self.groupBox_topics)        
        self.listTopics = QtWidgets.QListWidget(self.groupBox_topics)
        font_list = QtGui.QFont()
        font_list.setPointSize(11)
        self.listTopics.setFont(font_list)
        self.layout_topics.addWidget(self.listTopics)
        self.horizontalLayout.addWidget(self.groupBox_topics, 30)
        self.groupBox_content = QtWidgets.QGroupBox("Detaylı Anlatım", HelpScreen)
        self.layout_content = QtWidgets.QVBoxLayout(self.groupBox_content)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_content)
        font_text = QtGui.QFont()
        font_text.setPointSize(11)
        self.textBrowser.setFont(font_text)
        self.textBrowser.setOpenExternalLinks(True) 
        self.layout_content.addWidget(self.textBrowser)
        self.horizontalLayout.addWidget(self.groupBox_content, 70)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btnClose = QtWidgets.QPushButton(HelpScreen)
        self.btnClose.setText("Kapat")
        self.btnClose.setMinimumHeight(40)
        self.verticalLayout.addWidget(self.btnClose)
        QtCore.QMetaObject.connectSlotsByName(HelpScreen)