from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReportScreen(object):
    def setupUi(self, ReportScreen):
        ReportScreen.setObjectName("ReportScreen")
        ReportScreen.resize(1200, 800) 
        self.verticalLayout = QtWidgets.QVBoxLayout(ReportScreen)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.label_title = QtWidgets.QLabel(ReportScreen)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setText("Günlük Satış ve Performans Raporu")
        self.verticalLayout.addWidget(self.label_title)
        self.horizontalLayout_cards = QtWidgets.QHBoxLayout()       
        def create_info_group(title, obj_name):
            group = QtWidgets.QGroupBox(title)
            font_title = QtGui.QFont()
            font_title.setBold(True)
            group.setFont(font_title) 
            layout = QtWidgets.QVBoxLayout(group)
            label_val = QtWidgets.QLabel("₺0.00")
            label_val.setObjectName(obj_name)
            font_val = QtGui.QFont()
            font_val.setPointSize(14)
            font_val.setBold(True)
            label_val.setFont(font_val)
            label_val.setAlignment(QtCore.Qt.AlignCenter)
            layout.addWidget(label_val)
            return group, label_val
        self.gb_ciro, self.lbl_total_revenue = create_info_group("Toplam Ciro (Net)", "lbl_total_revenue")
        self.gb_maliyet, self.lbl_total_cost = create_info_group("Toplam Maliyet", "lbl_total_cost")
        self.gb_kar, self.lbl_total_profit = create_info_group("Net Kâr", "lbl_total_profit")
        self.gb_marj, self.lbl_margin = create_info_group("Kâr Marjı (%)", "lbl_margin")
        self.horizontalLayout_cards.addWidget(self.gb_ciro)
        self.horizontalLayout_cards.addWidget(self.gb_maliyet)
        self.horizontalLayout_cards.addWidget(self.gb_kar)
        self.horizontalLayout_cards.addWidget(self.gb_marj)
        self.verticalLayout.addLayout(self.horizontalLayout_cards)
        self.groupBox_filter = QtWidgets.QGroupBox("Tarih Aralığı", ReportScreen)
        self.layout_filter = QtWidgets.QHBoxLayout(self.groupBox_filter)       
        self.layout_filter.addWidget(QtWidgets.QLabel("Başlangıç:"))
        self.dateEdit_start = QtWidgets.QDateEdit(ReportScreen)
        self.dateEdit_start.setCalendarPopup(True)
        self.dateEdit_start.setDisplayFormat("dd.MM.yyyy")
        self.dateEdit_start.setDate(QtCore.QDate.currentDate().addDays(-30))
        self.layout_filter.addWidget(self.dateEdit_start)
        self.layout_filter.addWidget(QtWidgets.QLabel("Bitiş:"))
        self.dateEdit_end = QtWidgets.QDateEdit(ReportScreen)
        self.dateEdit_end.setCalendarPopup(True)
        self.dateEdit_end.setDisplayFormat("dd.MM.yyyy")
        self.dateEdit_end.setDate(QtCore.QDate.currentDate())
        self.layout_filter.addWidget(self.dateEdit_end)
        self.line = QtWidgets.QFrame()
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.layout_filter.addWidget(self.line)
        self.btn_daily_sales = QtWidgets.QPushButton("Raporu Getir", ReportScreen)
        self.btn_daily_sales.setMinimumHeight(30)
        self.layout_filter.addWidget(self.btn_daily_sales)       
        self.verticalLayout.addWidget(self.groupBox_filter)
        self.tableWidget_report = QtWidgets.QTableWidget(ReportScreen)
        self.tableWidget_report.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_report.setAlternatingRowColors(True)
        self.tableWidget_report.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.verticalLayout.addWidget(self.tableWidget_report)
        self.btn_close_report = QtWidgets.QPushButton("Kapat", ReportScreen)
        self.btn_close_report.setMinimumHeight(40)
        self.verticalLayout.addWidget(self.btn_close_report)
        QtCore.QMetaObject.connectSlotsByName(ReportScreen)